// Generated by https://quicktype.io

class Pelicula {
  bool adult;
  String backdropPath;
  List<int> genreIds;
  int id;
  String originalLanguage;
  String originalTitle;
  String overview;
  double popularity;
  String posterPath;
  String releaseDate;
  String title;
  bool video;
  double voteAverage;
  int voteCount;

  Pelicula ({
    required this.adult,
    required this.backdropPath,
    required this.genreIds,
    required this.id,
    required this.originalLanguage,
    required this.originalTitle,
    required this.overview,
    required this.popularity,
    required this.posterPath,
    required this.releaseDate,
    required this.title,
    required this.video,
    required this.voteAverage,
    required this.voteCount,
  });

 Pelicula.fromJsonmap(  Map <String, dynamic> json) {

    adult            =  json ['adult'];
    backdropPath     =  json ['backdropPath'];
    genreIds         =  json ['genre_ids'];
    id               =  json ['id'];
    originalLanguage =  json ['original_languaje'];
    originalTitle    =  json ['original_title'];
    overview         =  json ['overview'];
    popularity       =  json ['popularity'] /1 ;
    posterPath       =  json ['poster_path'];
    releaseDate      =  json ['release_date'];
    title            =  json ['title'];
    video            =  json ['video'];
    voteAverage      =  json ['vote_average'] /1 ;
    voteCount        =  json ['vote_count'];

 }
}
